# Config file for CelebA dataset (200k)

output_dir: '/home/dung/Project/Python/StyleGAN.pytorch/output'
structure: 'linear'
device_id: ('0')
dataset:
  img_dir: '/home/dung/Data/anh'
  folder: False
  resolution: 128
sched:
  epochs: [2,4,4,4,4,8]
